## **Refine-Library-DIA-NN**

In [1]:
import sys
sys.path.append("../../src/")
import createGPFLibraryDIANNStringent
import pandas as pd
from matplotlib_venn import venn2
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import pearsonr

In [3]:
diann_gpf_lib = createGPFLibraryDIANNStringent.run("diann-internals/report.tsv")

Reading DIA-NN results ...
105422 Precursors in the GPF library
Fetching Fragment ion information ...
Normalizing Intensities ...
filtering precursors ...
after quality filtering, 105185 precursors left

In [4]:
diann_gpf_lib

,ProteinId,ModifiedPeptideSequence,PeptideSequence,transition_group_id,PrecursorCharge,Protein.Q.Value,PG.Q.Value,NormalizedRetentionTime,LibraryIntensity,PrecursorMz,PrecursorIonMobility,Annotation,ProductMz,FragmentCharge,FragmentType,FragmentSeriesNumber
56614,Q8N5G2,LDLFSALGDAK,LDLFSALGDAK,LDLFSALGDAK2,2,0.000205,0.000207,92.163261,286.494374,575.311157,0.937504,y3^1,333.1768494,1,y,3
90380,Q9Y262,SEEEIDFLR,SEEEIDFLR,SEEEIDFLR2,2,0.000205,0.000207,73.584442,4584.519138,569.274780,0.907370,y3^1,435.2714233,1,y,3
90380,Q9Y262,SEEEIDFLR,SEEEIDFLR,SEEEIDFLR2,2,0.000205,0.000207,73.584442,8102.946762,569.274780,0.907370,y6^1,792.4250488,1,y,6
90380,Q9Y262,SEEEIDFLR,SEEEIDFLR,SEEEIDFLR2,2,0.000205,0.000207,73.584442,9020.805105,569.274780,0.907370,y5^1,663.3824463,1,y,5
90380,Q9Y262,SEEEIDFLR,SEEEIDFLR,SEEEIDFLR2,2,0.000205,0.000207,73.584442,6857.900485,569.274780,0.907370,y4^1,550.2984009,1,y,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62010,Q93074,LLLPLLLR,LLLPLLLR,LLLPLLLR2,2,0.000241,0.000242,99.898621,10000.000000,475.841675,0.859146,y5^1,611.4238892,1,y,5
74757,Q8N5C6,NIHHHQILAINR,NIHHHQILAINR,NIHHHQILAINR3,3,0.000241,0.000242,23.771704,2137.134426,489.276001,0.875089,y8^1,964.5686646,1,y,8
94202,Q96EB1,SNVTSFQR,SNVTSFQR,SNVTSFQR2,2,0.000241,0.000242,26.251547,6364.961208,469.738159,0.814672,y4^1,537.2779541,1,y,4
94202,Q96EB1,SNVTSFQR,SNVTSFQR,SNVTSFQR2,2,0.000241,0.000242,26.251547,10000.000000,469.738159,0.814672,y5^1,638.3256836,1,y,5
74757,Q8N5C6,NIHHHQILAINR,NIHHHQILAINR,NIHHHQILAINR3,3,0.000241,0.000242,23.771704,3039.981555,489.276001,0.875089,y7^1,827.5097656,1,y,7

In [5]:
diann_gpf_lib.to_csv("2025-03-06-diann-gpf-lib.tsv", sep='\t', index=False)

---

# **Only-Filter-DIA-NN**

In [2]:
diann_gpf_lib_only_filter = createGPFLibraryDIANNStringent.run("diann-internals/report.tsv", "../K562-Library-Generation/library.tsv", noIMCalibration=True, noRTCalibration=True, noIntensityCalibration=True)

Reading DIA-NN results ...
No RT Calibration
No IM Calibration
No Intensity Calibration
105422 Precursors in the GPF library
Fetching Fragment ion information ...
Loading library ...
Merging

In [3]:
diann_gpf_lib_only_filter

,ProteinId,ModifiedPeptideSequence,PeptideSequence,transition_group_id,PrecursorCharge,Protein.Q.Value,PG.Q.Value,NormalizedRetentionTime,PrecursorMz,PrecursorIonMobility,Annotation,ProductMz,LibraryIntensity,FragmentType,FragmentCharge,FragmentSeriesNumber
0,Q9BYW2,SHYYDSDRR,SHYYDSDRR,SHYYDSDRR3,3,0.000336,0.000299,6.756250,400.179382,0.734263,y8^3,371.1687012,2835.25830,y,3,8
1,Q9BYW2,SHYYDSDRR,SHYYDSDRR,SHYYDSDRR3,3,0.000336,0.000299,6.756250,400.179382,0.734263,b3^1,388.1615601,596.96050,b,1,3
2,Q9BYW2,SHYYDSDRR,SHYYDSDRR,SHYYDSDRR3,3,0.000336,0.000299,6.756250,400.179382,0.734263,y6^2,406.1882935,1355.62320,y,2,6
3,Q9BYW2,SHYYDSDRR,SHYYDSDRR,SHYYDSDRR3,3,0.000336,0.000299,6.756250,400.179382,0.734263,y7^2,487.7199707,10000.00000,y,2,7
4,Q9BYW2,SHYYDSDRR,SHYYDSDRR,SHYYDSDRR3,3,0.000336,0.000299,6.756250,400.179382,0.734263,b4^1,551.2248535,170.21275,b,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1264368,Q5VYK3,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK2,2,0.000872,0.000958,90.910843,1199.630371,1.406311,y17^2,980.4700317,3449.36700,y,2,17
1264369,Q5VYK3,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK2,2,0.000872,0.000958,90.910843,1199.630371,1.406311,y8^1,986.5265503,8080.16900,y,1,8
1264370,Q5VYK3,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK2,2,0.000872,0.000958,90.910843,1199.630371,1.406311,y10^1,1198.606201,7442.74800,y,1,10
1264371,Q5VYK3,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK2,2,0.000872,0.000958,90.910843,1199.630371,1.406311,y12^1,1458.689331,2151.89870,y,1,12
1264372,Q5VYK3,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK,VLLIESLATMEPDSRPELQEK2,2,0.000872,0.000958,90.910843,1199.630371,1.406311,y13^1,1559.737061,2087.23850,y,1,13

In [4]:
diann_gpf_lib_only_filter.to_csv("2025-06-05-diann-gpf-lib-only-filter.tsv", sep='\t', index=False)