## **Refine-Library-DIA-NN**

In [1]:
import sys
sys.path.append("../../src/")
import createGPFLibraryDIANNStringent
import pandas as pd
from matplotlib_venn import venn2
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import pearsonr
import polars as pl

In [3]:
diann_gpf_lib = createGPFLibraryDIANNStringent.run("diann-internals/report.tsv")

Reading DIA-NN results ...
124517 Precursors in the GPF library
Fetching Fragment ion information ...
Normalizing Intensities ...
filtering precursors ...
after quality filtering, 124444 precursors left

In [4]:
diann_gpf_lib

,ProteinId,ModifiedPeptideSequence,PeptideSequence,transition_group_id,PrecursorCharge,Protein.Q.Value,PG.Q.Value,NormalizedRetentionTime,LibraryIntensity,PrecursorMz,PrecursorIonMobility,Annotation,ProductMz,FragmentCharge,FragmentType,FragmentSeriesNumber
140661,P19838,YVC(UniMod:4)EGPSHGGLPGASSEK,YVCEGPSHGGLPGASSEK,YVC(UniMod:4)EGPSHGGLPGASSEK3,3,0.000193,0.000184,-3.328307,928.908441,611.280823,0.874608,y6^1,578.2780151,1,y,6
140661,P19838,YVC(UniMod:4)EGPSHGGLPGASSEK,YVCEGPSHGGLPGASSEK,YVC(UniMod:4)EGPSHGGLPGASSEK3,3,0.000193,0.000184,-3.328307,684.592447,611.280823,0.874608,b3^1,423.1696777,1,b,3
66593,O43615,LEESDVLQEAR,LEESDVLQEAR,LEESDVLQEAR2,2,0.000193,0.000184,22.565588,848.581291,644.822632,0.951391,b6^1,673.303894,1,b,6
140661,P19838,YVC(UniMod:4)EGPSHGGLPGASSEK,YVCEGPSHGGLPGASSEK,YVC(UniMod:4)EGPSHGGLPGASSEK3,3,0.000193,0.000184,-3.328307,3314.871955,611.280823,0.874608,y14^2,640.8151245,2,y,14
140661,P19838,YVC(UniMod:4)EGPSHGGLPGASSEK,YVCEGPSHGGLPGASSEK,YVC(UniMod:4)EGPSHGGLPGASSEK3,3,0.000193,0.000184,-3.328307,3845.695077,611.280823,0.874608,y7^1,675.3308105,1,y,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13159,P21580,C(UniMod:4)QAC(UniMod:4)LQDVTR,CQACLQDVTR,C(UniMod:4)QAC(UniMod:4)LQDVTR2,2,0.000193,0.000184,-0.015190,3178.021046,625.784424,0.927083,y6^1,731.4046021,1,y,6
13159,P21580,C(UniMod:4)QAC(UniMod:4)LQDVTR,CQACLQDVTR,C(UniMod:4)QAC(UniMod:4)LQDVTR2,2,0.000193,0.000184,-0.015190,2299.460883,625.784424,0.927083,b3^1,360.133606,1,b,3
126552,Q9HCI6,VFNTVYSLVK,VFNTVYSLVK,VFNTVYSLVK2,2,0.000193,0.000184,61.472523,6056.483340,585.331909,0.916885,y6^1,708.4290771,1,y,6
126552,Q9HCI6,VFNTVYSLVK,VFNTVYSLVK,VFNTVYSLVK2,2,0.000193,0.000184,61.472523,1105.640930,585.331909,0.916885,y7^1,809.4767456,1,y,7
126552,Q9HCI6,VFNTVYSLVK,VFNTVYSLVK,VFNTVYSLVK2,2,0.000193,0.000184,61.472523,6744.448352,585.331909,0.916885,y5^1,609.3606567,1,y,5

#### **All Peptide Precursors Have 12-4 Transitions**

In [5]:
diann_gpf_lib.groupby(['ModifiedPeptideSequence', 'PrecursorCharge']).count()['PeptideSequence'].max()

np.int64(12)

In [6]:
diann_gpf_lib.groupby(['ModifiedPeptideSequence', 'PrecursorCharge']).count()['PeptideSequence'].min()

np.int64(4)

This is sightly different from OpenSwath and is because the original library has more than 6 transitions.

In [7]:
diann_gpf_lib.to_csv("2025-06-18-peptdeep-nomods-gpf-refined-diann.tsv", sep='\t', index=False)

---

---

## **Create Library (Only Filter)**

Note needed to modify the script to use polars instead of pandas to ensure that program would not crash.

In [2]:
diann_gpf_lib_only_filter = createGPFLibraryDIANNStringent.run("diann-internals/report.tsv", "../PeptDeep-NoMods-In-Silico-Library-Generation/2025-06-10-in-silico-lib-no-mods_fix_mods_filtered.tsv.zst", noIMCalibration=True, noRTCalibration=True, noIntensityCalibration=True)

Reading DIA-NN results ...
No RT Calibration
No IM Calibration
No Intensity Calibration
124517 Precursors in the GPF library
Fetching Fragment ion information ...
Loading library ...
Merging

In [3]:
diann_gpf_lib_only_filter

,ProteinId,ModifiedPeptideSequence,PeptideSequence,transition_group_id,PrecursorCharge,Protein.Q.Value,PG.Q.Value,NormalizedRetentionTime,PrecursorMz,PrecursorIonMobility,Annotation,ProductMz,FragmentType,RelativeIntensity,ProductCharge,FragmentSeriesNumber,FragmentCharge
0,Q9Y4H2,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR2,2,0.000883,0.001267,24.321903,1016.532166,1.244625,y16^1,1364.69165,y,0.086569,1,16,1
1,Q9Y4H2,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR2,2,0.000883,0.001267,24.321903,1016.532166,1.244625,y7^1,659.3471069,y,0.063068,1,7,1
2,Q9Y4H2,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR2,2,0.000883,0.001267,24.321903,1016.532166,1.244625,y9^1,827.4370117,y,0.020327,1,9,1
3,Q9Y4H2,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR2,2,0.000883,0.001267,24.321903,1016.532166,1.244625,b6^1,427.22995,b,0.204516,1,6,1
4,Q9Y4H2,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR,AAAAAAAAVPSAGPAGPAPTSAAGR2,2,0.000883,0.001267,24.321903,1016.532166,1.244625,b7^1,498.2670593,b,0.349934,1,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345913,P50851,YYYWAVNPQDR,YYYWAVNPQDR,YYYWAVNPQDR2,2,0.000310,0.000251,47.193897,737.841125,1.027478,b4^1,676.2765503,b,0.098926,1,4,1
1345914,P50851,YYYWAVNPQDR,YYYWAVNPQDR,YYYWAVNPQDR2,2,0.000310,0.000251,47.193897,737.841125,1.027478,y4^1,515.2572632,y,0.538571,1,4,1
1345915,P50851,YYYWAVNPQDR,YYYWAVNPQDR,YYYWAVNPQDR2,2,0.000310,0.000251,47.193897,737.841125,1.027478,y5^1,629.3001709,y,0.706048,1,5,1
1345916,P50851,YYYWAVNPQDR,YYYWAVNPQDR,YYYWAVNPQDR2,2,0.000310,0.000251,47.193897,737.841125,1.027478,y6^1,728.3685913,y,0.716897,1,6,1
1345917,P50851,YYYWAVNPQDR,YYYWAVNPQDR,YYYWAVNPQDR2,2,0.000310,0.000251,47.193897,737.841125,1.027478,y7^1,799.4057007,y,1.000000,1,7,1

We see that this librry is larger which is expected because not filtering out any peptide precursors or fragments.

In [4]:
pl.from_pandas(diann_gpf_lib_only_filter).write_csv("2025-06-18-peptdeep-nomods-gpf-refined-diann-onlyFilter.tsv", separator='\t')